const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const STORE='quasarTicketsV1', TZ='America/Santo_Domingo';
let tickets=JSON.parse(localStorage.getItem(STORE)||'[]'), installPrompt;
const DRAWS={
  'La Primera':{draw:'12:00 PM',close:705},'La Suerte':{draw:'12:30 PM',close:735},
  'King Lottery':{draw:'12:55 PM',close:760},'Lotería Nacional Día':{draw:'2:30 PM',close:855},
  'Loteka':{draw:'7:55 PM',close:1180},'Lotería Real':{draw:'8:00 PM',close:1185},
  'Leidsa':{draw:'8:55 PM',close:1240},'Lotería Nacional Noche':{draw:'9:00 PM',close:1245}
};
const RULES={Quiniela:{count:1,min:10,max:5000,exposure:30000,pay:'70× / 8× / 4×',example:'12'},Palé:{count:2,min:10,max:500,exposure:5000,pay:'1,000×',example:'12 34'},Tripleta:{count:3,min:10,max:100,exposure:1000,pay:'10,000×',example:'12 34 56'}};
const money=n=>`RD$ ${Number(n).toLocaleString('es-DO',{minimumFractionDigits:2})}`;
const escapeHtml=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem(STORE,JSON.stringify(tickets));renderHistory()}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function drParts(){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).reduce((a,x)=>(a[x.type]=x.value,a),{})}
function drToday(){const p=drParts();return `${p.year}-${p.month}-${p.day}`}
function uid(){const p=drParts();return `${p.year.slice(-2)}${p.month}${p.day}-${String(Date.now()%10000).padStart(4,'0')}`}
function formatMinutes(m){const h=Math.floor(m/60),min=m%60;return `${h%12||12}:${String(min).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function getDrawState(){const p=drParts(),today=`${p.year}-${p.month}-${p.day}`,selected=$('#drawDate').value,now=Number(p.hour)*60+Number(p.minute),draw=DRAWS[$('#lottery').value];if(selected!==today)return{open:false,title:selected<today?'SORTEO CERRADO':'VENTA AÚN NO ABIERTA',note:selected<today?'La fecha seleccionada ya pasó.':'Abre a las 12:01 AM del día seleccionado.'};if(now<1)return{open:false,title:'VENTA AÚN NO ABIERTA',note:'Apertura automática a las 12:01 AM.'};if(now>=draw.close)return{open:false,title:'CERRADO PARA VENTA',note:`Cerró a las ${formatMinutes(draw.close)} · Sorteo ${draw.draw}.`};const left=draw.close-now;return{open:true,title:'ABIERTO PARA VENTA',note:`Cierra ${formatMinutes(draw.close)} · ${Math.floor(left/60)?`${Math.floor(left/60)} h `:''}${left%60} min restantes.`}}
function updateDraw(){const draw=DRAWS[$('#lottery').value];$('#drawTime').innerHTML=`<option>${draw.draw}</option>`;const state=getDrawState(),box=$('#drawStatus');box.classList.toggle('closed',!state.open);$('#statusTitle').textContent=state.title;$('#scheduleNote').textContent=state.note;$('#saleSubmit').disabled=!state.open}
function normalizePlay(type,raw){const nums=String(raw).match(/\d{2}/g)||[],rule=RULES[type];if(nums.length!==rule.count||nums.some(n=>Number(n)>99))return null;return type==='Quiniela'?nums[0]:nums.sort().join('-')}
function soldExposure(type,key,lottery,date){return tickets.filter(t=>t.lottery===lottery&&t.drawDate===date&&t.status!=='void').flatMap(t=>t.plays||[]).filter(p=>p.type===type&&normalizePlay(type,p.number)===key).reduce((s,p)=>s+Number(p.amount||0),0)}
function updatePlayRules(row){const type=$('.play-type',row).value,rule=RULES[type];$('.play-number',row).placeholder=rule.example;$('.play-amount',row).max=rule.max;$('.play-limit',row).textContent=`Mín. ${money(rule.min)} · Máx. ${money(rule.max)} · Pago ${rule.pay}`}
function addPlay(data={type:'Quiniela',number:'',amount:''}){const row=document.createElement('div');row.className='play-row';row.innerHTML=`<select class="play-type" aria-label="Tipo"><option>Quiniela</option><option>Palé</option><option>Tripleta</option></select><input class="play-number" aria-label="Números" inputmode="numeric" maxlength="8" required><input class="play-amount" aria-label="Monto" type="number" min="10" step="1" placeholder="RD$" required><button class="remove-play" type="button" aria-label="Eliminar">×</button><small class="play-limit"></small>`;$('.play-type',row).value=data.type;$('.play-number',row).value=data.number;$('.play-amount',row).value=data.amount;$('#plays').append(row);row.addEventListener('input',updateTotal);$('.play-type',row).onchange=()=>updatePlayRules(row);$('.remove-play',row).onclick=()=>{if($$('.play-row').length>1){row.remove();updateTotal()}};updatePlayRules(row);updateTotal()}
function updateTotal(){const rows=$$('.play-row'),total=rows.reduce((s,r)=>s+(Number($('.play-amount',r).value)||0),0);$('#saleTotal').textContent=money(total);$('#playCount').textContent=`${rows.length} jugada${rows.length===1?'':'s'}`}
function validatePlays(plays){const pending={};for(const p of plays){const rule=RULES[p.type],key=normalizePlay(p.type,p.number);if(!key)return `${p.type}: usa ${rule.count} número${rule.count>1?'s':''} de 00 a 99`;if(p.amount<rule.min||p.amount>rule.max)return `${p.type}: monto permitido ${money(rule.min)} a ${money(rule.max)}`;const bucket=`${p.type}|${key}`,base=soldExposure(p.type,key,$('#lottery').value,$('#drawDate').value),next=base+(pending[bucket]||0)+p.amount;if(next>rule.exposure)return `${p.type} ${key}: CERRADO. Disponible ${money(Math.max(0,rule.exposure-base-(pending[bucket]||0)))}`;pending[bucket]=(pending[bucket]||0)+p.amount}return null}
function qrFallback(text){let seed=[...text].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,2166136261),size=25,cells=[],finder=(x,y)=>x<7&&y<7||x>=size-7&&y<7||x<7&&y>=size-7;for(let y=0;y<size;y++)for(let x=0;x<size;x++){let on;if(finder(x,y)){const lx=x>=size-7?x-(size-7):x,ly=y>=size-7?y-(size-7):y;on=lx===0||ly===0||lx===6||ly===6||lx>=2&&lx<=4&&ly>=2&&ly<=4}else{seed=(seed*1664525+1013904223)>>>0;on=(seed>>>30)&1}if(on)cells.push(`<rect x="${x+2}" y="${y+2}" width="1" height="1"/>`)}return `<svg viewBox="0 0 ${size+4} ${size+4}"><rect width="100%" height="100%" fill="white"/><g fill="#000">${cells.join('')}</g></svg>`}
function paper(t){const qr=`https://quickchart.io/qr?size=180&margin=1&text=${encodeURIComponent(t.id)}`;return `<article class="paper"><header class="paper-header"><b>GRULODE · QUASAR DIGITAL</b><h2>QUASAR TICKET</h2><small>COMPROBANTE DE JUGADA</small></header><div class="paper-meta">TICKET: <b>${escapeHtml(t.id)}</b><br>FECHA: ${new Date(t.created).toLocaleString('es-DO')}<br>LOTERÍA: ${escapeHtml(t.lottery)}<br>SORTEO: ${escapeHtml(t.drawTime)} · ${escapeHtml(t.drawDate)}</div>${t.plays.map(p=>`<div class="paper-play"><b>${escapeHtml(p.type)}</b><span>${escapeHtml(p.number)}</span><span>${money(p.amount)}</span></div>`).join('')}<div class="paper-total"><span>TOTAL</span><span>${money(t.total)}</span></div><div class="qr-code"><img src="${qr}" alt="QR del ticket">${qrFallback(t.id)}</div><div class="paper-footer"><b>${escapeHtml(t.id)}</b><small>Premios sujetos a validación.<br>Desarrollado por Quasar Digital</small></div></article>`}
function openTicket(t){$('#printTicket').innerHTML=paper(t);$('#ticketDialog').showModal()}
$('#saleForm').addEventListener('submit',e=>{e.preventDefault();const state=getDrawState();if(!state.open)return toast(`Venta bloqueada: ${state.title}`);const plays=$$('.play-row').map(r=>({type:$('.play-type',r).value,number:$('.play-number',r).value.trim(),amount:Number($('.play-amount',r).value)})),error=validatePlays(plays);if(error)return toast(error);const total=plays.reduce((s,p)=>s+p.amount,0),ticket={id:uid(),lottery:$('#lottery').value,drawDate:$('#drawDate').value,drawTime:$('#drawTime').value,plays,total,created:new Date().toISOString(),status:'active',prize:0};tickets.unshift(ticket);save();openTicket(ticket);e.target.reset();$('#drawDate').value=drToday();updateDraw();$('#plays').innerHTML='';addPlay()});
$('#addPlay').onclick=()=>addPlay();$('#closeTicket').onclick=()=>$('#ticketDialog').close();$('#printButton').onclick=()=>window.print();
function renderHistory(filter=''){const list=$('#ticketList'),shown=tickets.filter(t=>`${t.id} ${t.lottery}`.toLowerCase().includes(filter.toLowerCase()));list.innerHTML=shown.length?shown.map(t=>`<button class="ticket-item" data-id="${escapeHtml(t.id)}"><div><h3>${escapeHtml(t.id)}</h3><p>${escapeHtml(t.lottery)} · ${new Date(t.created).toLocaleDateString('es-DO')}</p><span class="status ${t.status==='paid'?'paid':''}">${t.status==='paid'?'PAGADO':'VIGENTE'}</span></div><strong>${money(t.total)}</strong></button>`).join(''):'<div class="empty">Aún no hay tickets guardados.</div>';$$('.ticket-item',list).forEach(b=>b.onclick=()=>openTicket(tickets.find(t=>t.id===b.dataset.id)));$('#ticketStat').textContent=tickets.length;$('#salesStat').textContent=money(tickets.reduce((s,t)=>s+t.total,0)).replace('.00','');$('#paidStat').textContent=money(tickets.reduce((s,t)=>s+(t.status==='paid'?t.prize:0),0)).replace('.00','')}
$('#historySearch').oninput=e=>renderHistory(e.target.value);
function lookup(id){const t=tickets.find(x=>x.id.toLowerCase()===id.trim().toLowerCase()),box=$('#checkResult');if(!t){box.innerHTML='<div class="card result-card"><h3>Ticket no encontrado</h3><p class="microcopy">Verifica la numeración en este dispositivo.</p></div>';return}box.innerHTML=`<div class="card result-card"><h3>Ticket ${escapeHtml(t.id)}</h3><div class="result-meta"><span>Estado</span><b>${t.status==='paid'?'PAGADO':'VIGENTE'}</b></div><div class="result-meta"><span>Lotería</span><b>${escapeHtml(t.lottery)} · ${escapeHtml(t.drawTime)}</b></div><div class="result-meta"><span>Apostado</span><b>${money(t.total)}</b></div>${t.status==='paid'?`<div class="prize-box"><small>Premio pagado</small><strong>${money(t.prize)}</strong></div>`:`<label style="margin-top:16px">Números ganadores (1.º, 2.º, 3.º)</label><div class="winning-inputs"><input maxlength="2" inputmode="numeric" placeholder="00"><input maxlength="2" inputmode="numeric" placeholder="00"><input maxlength="2" inputmode="numeric" placeholder="00"></div><button class="secondary calc-button" type="button">Calcular premio</button><div class="prize-output"></div>`}</div>`;const calc=$('.calc-button',box);if(calc)calc.onclick=()=>calculate(t,box)}
function calculate(t,box){const winners=$$('.winning-inputs input',box).map(i=>i.value.padStart(2,'0'));if(winners.some(x=>!/^[0-9]{2}$/.test(x)))return toast('Introduce los tres resultados');let prize=0;t.plays.forEach(p=>{const nums=p.number.match(/\d{2}/g)||[];if(p.type==='Quiniela'){const pos=winners.indexOf(nums[0]);prize+=pos===0?p.amount*70:pos===1?p.amount*8:pos===2?p.amount*4:0}if(p.type==='Palé'&&nums.slice(0,2).every(n=>winners.includes(n)))prize+=p.amount*1000;if(p.type==='Tripleta'&&nums.slice(0,3).every(n=>winners.includes(n)))prize+=p.amount*10000});t.prize=prize;$('.prize-output',box).innerHTML=`<div class="prize-box"><small>Premio calculado</small><strong>${money(prize)}</strong></div>${prize>0?'<button class="pay-button" type="button">Marcar como pagado</button>':''}<p class="microcopy">Pagos GRULODE: Quiniela 70×/8×/4×, Palé 1,000×, Tripleta 10,000×.</p>`;const pay=$('.pay-button',box);if(pay)pay.onclick=()=>{t.status='paid';t.paidAt=new Date().toISOString();save();lookup(t.id);toast('Pago registrado')}}
$('#lookupForm').onsubmit=e=>{e.preventDefault();lookup($('#ticketNumber').value)};
$('#scanButton').onclick=async()=>{const msg=$('#scanMessage'),video=$('#camera');if(!('BarcodeDetector'in window)){msg.textContent='Usa la numeración manual en este navegador.';return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.hidden=false;video.srcObject=stream;await video.play();const detector=new BarcodeDetector({formats:['qr_code']}),timer=setInterval(async()=>{const codes=await detector.detect(video);if(codes[0]){clearInterval(timer);stream.getTracks().forEach(t=>t.stop());video.hidden=true;const raw=codes[0].rawValue.replace('QUASAR:','');$('#ticketNumber').value=raw;lookup(raw)}},500);setTimeout(()=>{clearInterval(timer);stream.getTracks().forEach(t=>t.stop());video.hidden=true},30000)}catch{msg.textContent='No se pudo abrir la cámara. Usa la numeración.'}};
$$('.bottom-nav button').forEach(b=>b.onclick=()=>{$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${b.dataset.screen}`));if(b.dataset.screen==='tickets')renderHistory();scrollTo(0,0)});
$('#exportButton').onclick=()=>{const blob=new Blob([JSON.stringify(tickets,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`quasar-tickets-${drToday()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#clearButton').onclick=()=>{if(confirm('¿Borrar todos los tickets de este dispositivo?')){tickets=[];save();toast('Datos locales borrados')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{installPrompt?.prompt();await installPrompt?.userChoice;$('#installButton').hidden=true};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
const now=new Date();$('#todayLabel').textContent=new Intl.DateTimeFormat('es-DO',{timeZone:TZ,weekday:'long',day:'numeric',month:'long'}).format(now).toUpperCase();$('#drawDate').value=drToday();$('#lottery').onchange=updateDraw;$('#drawDate').onchange=updateDraw;updateDraw();addPlay();renderHistory();setInterval(updateDraw,30000);
